#!/bin/bash
#Variablen:
ordner="/opt/USER/screenshooter/"
log="/opt/USER/screenshooter/screenshooter.log"
ssh="1"
host="ssh-or-ftp.host"
path="/path/to/directory"
user="user-remote"
pass="ftp-pass"
http="https://host/path/"

zeitstempel="$(date +%d-%m-%Y_%H-%M-%S)"

#Script:
cd "${ordner}"
xfce4-screenshooter -r -o 'cat' > ${zeitstempel}.png
if [ -e ${zeitstempel}.png ]
	then
		sha1sum="$(sha1sum ${zeitstempel}.png | cut -d' ' -f1)"
		if [ "$ssh" == "1" ] 
			then	
				scp ${zeitstempel}.png ${user}@${host}:${path}${sha1sum}.png
			else
				curl -T ${zeitstempel}.png -u ${user}:${pass} ${host}${path}${sha1sum}.png
		fi
		rm "${zeitstempel}.png"
		echo "$zeitstempel URL: ${http}${sha1sum}.png" >> ${log}
		echo "${http}${sha1sum}.png" | xclip -selection c
		notify-send -t 3000 "Screenshot hochgeladen!"
	else
		exit 1
fi
