#!/bin/bash
#Variablen:
ordner="/home/robin/.bin/screenshooter/"
script="screenshooter"
log="/home/robin/.bin/screenshooter/screenshooter.log"
ftp="ftp://robingroppe.de/htdocs/screens/"
ftpuser="user"
ftppass="password"
http="http://www.robingroppe.de/screens/"
zeitstempel="$(date +%d-%m-%Y_%H-%M-%S)"
#Script:
cd "${ordner}"
xfce4-screenshooter -r -o 'cat' > ${zeitstempel}.png
if [ -e ${zeitstempel}.png ]
	then
		sha1sum="$(sha1sum ${zeitstempel}.png | cut -d' ' -f1)"
		curl -T ${zeitstempel}.png -u ${ftpuser}:${ftppass} ${ftp}${sha1sum}.png
		rm "${zeitstempel}.png"
		echo "$zeitstempel URL: ${http}${sha1sum}.png" >> ${log}
		echo "${http}${sha1sum}.png" | xclip -selection c
		notify-send -t 3000 "Screenshot hochgeladen!"
	else
		exit 1
fi
