#!/bin/bash
#Variablen:
ordner="/home/user/Bin/screenshooter/"
log="/home/user/Bin/screenshooter/screenshooter.log"
ftp="ftp://server.com/htdocs/screens/"
ftpuser="user"
ftppass="password"
http="https://server.com/screens/"

#Script:
zeitstempel="$(date +%d-%m-%Y_%H-%M-%S)"
cd "${ordner}"
gnome-screenshot -a -f ${zeitstempel}.png
if [ -e ${zeitstempel}.png ]
	then
		sha1sum="$(sha1sum ${zeitstempel}.png | cut -d' ' -f1)"
		curl -T ${zeitstempel}.png -u ${ftpuser}:${ftppass} ${ftp}${sha1sum}.png
		rm "${zeitstempel}.png"
		echo "$zeitstempel URL: ${http}${sha1sum}.png" >> ${log}
		echo "${http}${sha1sum}.png" | xclip -selection c
		notify-send -t 3000 "Screenshot hochgeladen!"
	else
		exit 1
fi
